project_id    = "ibtracs-mapper"
root_domain   = "ibtracs-mapper.com"
backend_image = "europe-west1-docker.pkg.dev/ibtracs-mapper/ibtracs-mapper/backend-api:latest"
updater_image = "europe-west1-docker.pkg.dev/ibtracs-mapper/ibtracs-mapper/db-updater:latest"
backend_cors_origins = "https://ibtracs-mapper.com,http://localhost:5173"
